// key corresponds to movie id
const images = {
	1: '/images/Jurrassic_Park_3.jpg',
	2: '/images/Lord_of_the_Rings.jpg',
	3: '/images/The_Conjuring.jpg',
	4: '/images/Avatar.jpg',
	5: '/images/Titanic.jpg',
	6: '/images/The_Avengers.jpg',
	7: '/images/Toy_Story.jpg',
	8: '/images/Resident_Evil.jpg',
	9: '/images/Finding_Nemo.jpg',
	10: '/images/Aladdin.jpg',
	11: '/images/Spirited_Away.jpg',
	12: '/images/Us.jpg',
	13: '/images/The_Grand_Budapest_Hotel.jpg',
	14: '/images/A_Quiet_Place_(2018).jpg',
	15: '/images/The_Terminator.jpg',
	16: '/images/Hereditary_(2018).jpg',
	17: '/images/Isle_of_Dogs.jpg',
	18: '/images/As_Above,_So_Below.jpg',
	19: '/images/Monty_Python_and_The_Holy_Grail.jpg',
	20: '/images/The_Texas_Chain_Saw_Massacre_(1974).jpg',
	21: '/images/Mean_Girls.jpg',
	22: '/images/The_Black_Panther(2018).jpg',
	23: "/images/Ferris_Bueller's_Day_Off.jpg",
	24: '/images/Spider_Man_Into_the_Spider-Verse_(2018).jpg',
	25: '/images/Logan_(2017).jpg',
	26: '/images/Avengers_Endgame_(2019).jpg',
	27: '/images/Blade_Runner_2049_(2017).jpg',
	28: "/images/Pan's_Labyrinth_(2006).jpg",
};

module.exports = images;
